# -*- coding: utf-8 -*-
"""Untitled0.ipynb の7/29

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgNuAWstxFVkyWmZZXYnZrdGr8BnR9T8
"""

big_spend = kakeibo_df[kakeibo_df['金額（円）'] <= -10000]
print(big_spend)

shokuhi = kakeibo_df[kakeibo_df['大項目']=='食費']['金額（円）'].sum()
print('今月の食費合計:', shokuhi)

rank = kakeibo_df.groupby('大項目')['金額（円）'].sum().sort_values(ascending=False)
print(rank.head(3))

print(kakeibo_df['金額（円）'].head(10))  # 上から10行くらい見てみる
print(kakeibo_df.dtypes)  # カラムごとの型を確認

import pandas as pd
kakeibo_df=pd.read_csv('収入・支出詳細_2025-07-01_2025-07-31 (2).csv',encoding='shift-jis')

print(kakeibo_df)

print(df)

import pandas as pd
from pandasql import sqldf
data = {'user_id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']}
data_df = pd.DataFrame(data)

query = "SELECT * FROM data_df WHERE user_id = 3;"
result = sqldf(query)

print(result)

df['金額（円）'] = pd.to_numeric(df['金額（円）'], errors='coerce')

query = "SELECT * FROM data_df WHERE user_id = 1;"
result = sqldf(query)

print(result)

query='select max(値段)as 最大値 FROM df;'
result=sqldf(query,locals())

print(result)

import pandas as pd
from pandasql import sqldf
ra_mencacaku={'ラーメン':['醤油','塩','豚骨',Z],'値段':[1000,1500,2000,0]}
df=pd.DataFrame(ra_mencacaku)

print(df)

# Commented out IPython magic to ensure Python compatibility.
# %pip install pandas pandasql #import pandas as pd とfrom pandasql import sqldfもセットの方が良いらしい

Z="Hello,Phoenix! Pythonの世界にようこそ"
print(Z)