from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader

PDF_OUT = "reports/anomaly_report.pdf"
IMG     = "reports/anomalies.png"

c = canvas.Canvas(PDF_OUT, pagesize=A4)
w, h = A4
c.setFont("Helvetica", 14)
c.drawString(40, h-40, "Ad Spend Anomaly Report")
c.setFont("Helvetica", 10)
c.drawString(40, h-60, "Generated by Python (pandas + matplotlib)")
c.drawImage(ImageReader(IMG), 40, 200, width=w-80, height=320, preserveAspectRatio=True)
c.showPage(); c.save()
print("OK:", PDF_OUT)
